<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends EntityRepository
{
	/****
	returns the number of entity's rows
	@return int
	*/
	public function count() {
		$query = $this->createQueryBuilder('e')->select('count(e)')->getQuery();
		return $query->getSingleScalarResult();
	}
	public function notSlug() {
		$query = $this->createQueryBuilder('p')->select('p')->where("p.id = p.slug")->getQuery();
		return $query->execute();
	}
}
