api_user_register:
  path: /api/user/register/{token}/{purchase}/
  defaults: { _controller: UserBundle:User:api_register}
  methods: POST
api_user_edit:
  path: /api/user/edit/{token}/{purchase}/
  defaults: { _controller: UserBundle:User:api_edit}
  methods: POST
api_user_token:
  path: /api/user/token/{token}/{purchase}/
  defaults: { _controller: UserBundle:User:api_token}
  methods: POST
api_user_login:
  path: /api/user/login/{token}/{purchase}/
  defaults: { _controller: UserBundle:User:api_login}
  methods: POST
user_user_index:
  path: /admin/users/index.html
  defaults: { _controller: UserBundle:User:index}
user_user_edit:
  path: /admin/users/edit/{id}.html
  defaults: { _controller: UserBundle:User:edit}
  requirements:
      id:  \d+
user_user_comments:
  path: /admin/users/comments/{id}.html
  defaults: { _controller: UserBundle:User:comments}
  requirements:
      id:  \d+
user_admin_user_subscriptions:
  path: /admin/users/subscriptions/{id}.html
  defaults: { _controller: UserBundle:User:admin_subscriptions}
  requirements:
      id:  \d+
user_user_ratings:
  path: /admin/users/ratings/{id}.html
  defaults: { _controller: UserBundle:User:ratings}
  requirements:
      id:  \d+
user_user_delete:
  path: /admin/users/delete/{id}.html
  defaults: { _controller: UserBundle:User:delete}
  requirements:
      id:  \d+
api_user_check:
    path: /api/user/check/{id}/{key}/{token}/{purchase}/
    defaults: { _controller: UserBundle:User:api_check}
    methods: GET
api_user_email:
    path: /api/user/email/{email}/{token}/{purchase}/
    defaults: { _controller: UserBundle:Resetting:api_email}
    methods: GET
api_user_request:
    path: /api/user/request/{key}/{token}/{purchase}/
    defaults: { _controller: UserBundle:Resetting:api_request}
    methods: GET
api_user_reset:
    path: /api/user/reset/{id}/{key}/{new_password}/{token}/{purchase}/
    defaults: { _controller: UserBundle:Resetting:api_reset}
    methods: GET
api_user_change_password:
  path: /api/user/password/{id}/{password}/{new_password}/{token}/{purchase}/
  defaults: { _controller: UserBundle:User:api_change_password}
  methods: GET
user_user_subscriptions:
    path:  /profile/subscriptions.html
    defaults: { _controller: FOSUserBundle:User:subscriptions }
ajax_login:
    path:  /ajax/
    defaults: { _controller: FOSUserBundle:Security:ajaxlogin }
user_login:
    path:  /login/
    defaults: { _controller: FOSUserBundle:Security:login }
admin_login:
    path:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }
admin_check:
    path:  /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }
admin_logout:
    path:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }
admin_change_password:
    path:  /admin/change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:adminchangePassword }
fos_user_resetting_reseted:
    path: /resetting/reseted
    defaults: { _controller: FOSUserBundle:Resetting:reseted }
fos_user_myprofile_edit:
    path: /profile/edit.html
    defaults: { _controller: FOSUserBundle:User:myedit }